const TEMPLATE = /plugin_name/i;
const TEMPLATE_FOR_REPLACE_LOWERCASE = /plugin_name/g;
const TEMPLATE_FOR_REPLACE_CAPITALCASE = /Plugin_Name/g;

module.exports = {
    TEMPLATE,
    TEMPLATE_FOR_REPLACE_LOWERCASE,
    TEMPLATE_FOR_REPLACE_CAPITALCASE,
};
